name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "oeaboardsint"
          ado_project: "oeaboardsint"
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
          log_level: 100
